"""scripts/setup_git_hooks.sh must fail loudly, not silently, and must never
report success without a real, working pre-commit-managed hook in place.

Runs the actual script (not a reimplementation) against a throwaway git
repo, with a curated PATH built from stub `gitleaks`/`pre-commit`
executables plus only the specific coreutils the script needs -- no real
network access or package installer is reachable, so every scenario here is
hermetic and fast.
"""

from __future__ import annotations

import os
import shutil
import stat
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "scripts" / "setup_git_hooks.sh"

# Only these are ever invoked by the script (besides the stubbed
# gitleaks/pre-commit); deliberately excludes python3/pip3/pipx so the
# "no installer available" scenarios are hermetic regardless of what's
# actually installed on the host running the test.
REQUIRED_TOOLS = ["git", "curl", "tar", "mkdir", "chmod", "grep", "mktemp", "uname", "tr", "bash", "sh"]

GITLEAKS_STUB = """#!/bin/sh
if [ "$1" = "version" ]; then
  echo "8.18.4"
  exit 0
fi
exit 0
"""

PRE_COMMIT_STUB_GOOD = """#!/bin/sh
if [ "$1" = "install" ]; then
  hooks_dir="$(git rev-parse --git-common-dir)/hooks"
  mkdir -p "$hooks_dir"
  cat > "$hooks_dir/pre-commit" <<'HOOK'
#!/usr/bin/env python3
# File generated by pre-commit: https://pre-commit.com
# ID: stub-test-hook
HOOK
  chmod +x "$hooks_dir/pre-commit"
  exit 0
fi
exit 0
"""

WRONG_VERSION_GITLEAKS_STUB = """#!/bin/sh
if [ "$1" = "version" ]; then
  echo "1.2.3"
  exit 0
fi
exit 0
"""

# Fakes the download step so the shadowed-PATH scenario below stays
# hermetic (no real network access reachable in this test environment):
# writes a placeholder in place of a real archive. Paired with FAKE_TAR,
# which ignores that placeholder and materializes a real, correctly
# versioned gitleaks binary directly at the requested destination -- what a
# genuine `tar -xzf ... gitleaks` would produce from the pinned release.
FAKE_CURL = """#!/bin/sh
out=""
while [ $# -gt 0 ]; do
  case "$1" in
    -o) out="$2"; shift 2 ;;
    *) shift ;;
  esac
done
: > "$out"
"""

FAKE_TAR = """#!/bin/sh
dest=""
prev=""
for arg in "$@"; do
  if [ "$prev" = "-C" ]; then
    dest="$arg"
  fi
  prev="$arg"
done
cat > "$dest/gitleaks" <<'BIN'
#!/bin/sh
if [ "$1" = "version" ]; then
  echo "8.18.4"
  exit 0
fi
exit 0
BIN
chmod +x "$dest/gitleaks"
"""

# Simulates a broken/unexpected pre-commit install that writes a hook file
# without the marker pre-commit normally stamps -- the script must refuse
# to call this success.
PRE_COMMIT_STUB_NO_MARKER = """#!/bin/sh
if [ "$1" = "install" ]; then
  hooks_dir="$(git rev-parse --git-common-dir)/hooks"
  mkdir -p "$hooks_dir"
  cat > "$hooks_dir/pre-commit" <<'HOOK'
#!/bin/sh
echo "not actually managed by pre-commit"
HOOK
  chmod +x "$hooks_dir/pre-commit"
  exit 0
fi
exit 0
"""


def _minimal_path() -> str:
    dirs: list[str] = []
    for tool in REQUIRED_TOOLS:
        found = shutil.which(tool)
        assert found, f"test environment is missing required tool {tool!r}"
        d = str(Path(found).parent)
        if d not in dirs:
            dirs.append(d)
    return os.pathsep.join(dirs)


def _write_stub(bin_dir: Path, name: str, content: str) -> None:
    path = bin_dir / name
    path.write_text(content)
    path.chmod(path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)


def _run_script(tmp_path: Path, *, pre_commit_stub: str | None) -> subprocess.CompletedProcess[str]:
    repo = tmp_path / "repo"
    repo.mkdir()
    subprocess.run(["git", "init", "-q"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.name", "Test"], cwd=repo, check=True)

    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    _write_stub(bin_dir, "gitleaks", GITLEAKS_STUB)
    if pre_commit_stub is not None:
        _write_stub(bin_dir, "pre-commit", pre_commit_stub)

    env = {
        "PATH": f"{bin_dir}{os.pathsep}{_minimal_path()}",
        "HOME": str(tmp_path / "home"),
    }
    (tmp_path / "home").mkdir(exist_ok=True)

    return subprocess.run(
        ["bash", str(SCRIPT)],
        cwd=repo,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )


def test_fails_when_no_pre_commit_installer_is_reachable(tmp_path):
    result = _run_script(tmp_path, pre_commit_stub=None)

    assert result.returncode != 0
    assert "pre-commit" in (result.stdout + result.stderr).lower()
    hook = tmp_path / "repo" / ".git" / "hooks" / "pre-commit"
    assert not hook.exists() or "File generated by pre-commit" not in hook.read_text()


def test_installs_a_real_hook_and_reports_success(tmp_path):
    result = _run_script(tmp_path, pre_commit_stub=PRE_COMMIT_STUB_GOOD)

    assert result.returncode == 0, result.stdout + result.stderr
    hook = tmp_path / "repo" / ".git" / "hooks" / "pre-commit"
    assert hook.exists()
    assert hook.stat().st_mode & stat.S_IXUSR, "installed hook must be executable"
    assert "File generated by pre-commit" in hook.read_text()


def test_fails_when_installed_hook_has_no_pre_commit_marker(tmp_path):
    """A pre-commit look-alike that doesn't actually carry pre-commit's own
    marker must not be reported as a successful install -- this is the
    check that catches a stale/hand-written hook silently shadowing
    gitleaks."""

    result = _run_script(tmp_path, pre_commit_stub=PRE_COMMIT_STUB_NO_MARKER)

    assert result.returncode != 0
    assert "does not look like a pre-commit-managed hook" in (result.stdout + result.stderr)


def test_fails_when_core_hooks_path_overrides_the_standard_hooks_dir(tmp_path):
    """core.hooksPath pointed elsewhere would make git skip the hook
    pre-commit just installed -- every commit would silently bypass
    gitleaks. The script must refuse to report success in that state."""

    repo = tmp_path / "repo"
    repo.mkdir()
    subprocess.run(["git", "init", "-q"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.name", "Test"], cwd=repo, check=True)
    (repo / "other-hooks").mkdir()
    subprocess.run(["git", "config", "core.hooksPath", "other-hooks"], cwd=repo, check=True)

    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    _write_stub(bin_dir, "gitleaks", GITLEAKS_STUB)
    _write_stub(bin_dir, "pre-commit", PRE_COMMIT_STUB_GOOD)

    env = {"PATH": f"{bin_dir}{os.pathsep}{_minimal_path()}", "HOME": str(tmp_path / "home")}
    (tmp_path / "home").mkdir(exist_ok=True)

    result = subprocess.run(
        ["bash", str(SCRIPT)],
        cwd=repo,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode != 0
    assert "core.hooksPath" in (result.stdout + result.stderr)


def test_fails_when_a_wrong_version_gitleaks_shadows_the_install_dir_on_path(tmp_path):
    """The pre-commit hook invokes unqualified `gitleaks` (language: system
    in .pre-commit-config.yaml), resolved via PATH at commit time -- not
    the absolute GITLEAKS_INSTALL_DIR path this script installs to. If a
    different-version gitleaks (e.g. a stray `brew install gitleaks`)
    resolves earlier on PATH than GITLEAKS_INSTALL_DIR, the script must not
    report success just because the pinned build landed at the install
    path: the hook would still silently run the wrong version."""

    repo = tmp_path / "repo"
    repo.mkdir()
    subprocess.run(["git", "init", "-q"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.name", "Test"], cwd=repo, check=True)

    shadow_dir = tmp_path / "shadow-gitleaks"
    shadow_dir.mkdir()
    _write_stub(shadow_dir, "gitleaks", WRONG_VERSION_GITLEAKS_STUB)

    tool_dir = tmp_path / "tools"
    tool_dir.mkdir()
    _write_stub(tool_dir, "curl", FAKE_CURL)
    _write_stub(tool_dir, "tar", FAKE_TAR)
    _write_stub(tool_dir, "pre-commit", PRE_COMMIT_STUB_GOOD)

    install_dir = tmp_path / "install-dir"

    env = {
        "PATH": os.pathsep.join([str(shadow_dir), str(tool_dir), str(install_dir), _minimal_path()]),
        "HOME": str(tmp_path / "home"),
        "GITLEAKS_INSTALL_DIR": str(install_dir),
    }
    (tmp_path / "home").mkdir(exist_ok=True)

    result = subprocess.run(
        ["bash", str(SCRIPT)],
        cwd=repo,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )

    combined = result.stdout + result.stderr
    assert result.returncode != 0, combined
    assert "a different gitleaks resolves earlier on path" in combined.lower()
    assert str(shadow_dir) in combined
    # The pinned binary must actually have been installed to the install
    # dir -- this failure is specifically about the unqualified `gitleaks`
    # PATH resolution, not about the install itself failing.
    installed = install_dir / "gitleaks"
    assert installed.exists()
    assert subprocess.run([str(installed), "version"], capture_output=True, text=True).stdout.strip() == "8.18.4"
